#!/usr/bin/env node
/**
 * PWA Validation Script
 * Validates that all PWA requirements are met
 */

const fs = require('fs')
const path = require('path')

const publicDir = path.join(__dirname, '../public')
const viteConfigPath = process.env.VITE_CONFIG_PATH
  ? path.resolve(process.env.VITE_CONFIG_PATH)
  : path.join(__dirname, '../vite.config.js')

let errors = 0
let warnings = 0

function checkFile(filePath, description) {
  if (fs.existsSync(filePath)) {
    console.log(`✅ ${description}`)
    return true
  } else {
    console.error(`❌ ${description} - File not found: ${filePath}`)
    errors++
    return false
  }
}

function validateJSON(filePath, description) {
  try {
    const content = fs.readFileSync(filePath, 'utf8')
    JSON.parse(content)
    console.log(`✅ ${description} - Valid JSON`)
    return true
  } catch (e) {
    console.error(`❌ ${description} - Invalid JSON: ${e.message}`)
    errors++
    return false
  }
}

function validateManifest() {
  const manifestPath = path.join(publicDir, 'manifest.json')
  if (!checkFile(manifestPath, 'Manifest file exists')) return
  if (!validateJSON(manifestPath, 'Manifest JSON')) return

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))

  // Check required fields
  const requiredFields = ['name', 'short_name', 'start_url', 'display', 'icons']
  requiredFields.forEach((field) => {
    if (manifest[field]) {
      console.log(`✅ Manifest has '${field}' field`)
    } else {
      console.error(`❌ Manifest missing required field: '${field}'`)
      errors++
    }
  })

  // Check icons
  if (Array.isArray(manifest.icons) && manifest.icons.length > 0) {
    console.log(`✅ Manifest has ${manifest.icons.length} icon(s)`)
  } else {
    console.error('❌ Manifest has no icons')
    errors++
  }
}

function validateServiceWorker() {
  // Service worker is now generated by VitePWA plugin during build
  // Check for the VitePWA configuration in vite.config.js
  if (!checkFile(viteConfigPath, 'vite.config.js exists')) return

  const content = fs.readFileSync(viteConfigPath, 'utf8')

  // Check for VitePWA plugin configuration
  if (content.includes('VitePWA')) {
    console.log('✅ VitePWA plugin configured')
  } else {
    console.error('❌ VitePWA plugin not configured')
    errors++
    return
  }

  // Check for navigation fallback configuration
  if (content.includes('navigateFallback')) {
    console.log('✅ Navigation fallback configured for SPA routing')
  } else {
    console.warn('⚠️  Navigation fallback not explicitly configured')
    warnings++
  }

  // Check for workbox configuration
  if (content.includes('workbox:')) {
    console.log('✅ Workbox configuration present')
  } else {
    console.warn('⚠️  Workbox configuration not found')
    warnings++
  }
}

function validateIcons() {
  const icons = ['icon-192x192.svg', 'icon-512x512.svg']
  icons.forEach((icon) => {
    checkFile(path.join(publicDir, icon), `Icon file: ${icon}`)
  })
}

function validateIndexHTML() {
  const indexPath = path.join(publicDir, 'index.html')
  if (!checkFile(indexPath, 'index.html exists')) return

  const content = fs.readFileSync(indexPath, 'utf8')

  // Check for manifest link
  // Note: VitePWA plugin automatically injects the manifest link during build
  if (content.includes('rel="manifest"')) {
    console.log('✅ index.html links to manifest')
  } else {
    console.log(
      'ℹ️  Manifest link is injected during build by VitePWA plugin'
    )
  }

  // Check for theme-color
  if (content.includes('name="theme-color"')) {
    console.log('✅ index.html has theme-color meta tag')
  } else {
    console.warn('⚠️  index.html missing theme-color meta tag')
    warnings++
  }
}

function validateServiceWorkerRegistration() {
  // Service worker registration is now handled automatically by VitePWA plugin
  // The plugin injects the registration script during build
  const content = fs.readFileSync(viteConfigPath, 'utf8')

  if (content.includes('registerType:')) {
    console.log('✅ Service worker auto-registration configured via VitePWA')
  } else {
    console.warn(
      '⚠️  Service worker registration type not explicitly configured'
    )
    warnings++
  }

  // Note: The actual registration script (registerSW.js) is generated during build
  console.log(
    'ℹ️  Service worker registration script is generated during build by VitePWA'
  )
}

console.log('🔍 Validating PWA Implementation...\n')

console.log('📄 Manifest Validation:')
validateManifest()

console.log('\n⚙️  Service Worker Validation:')
validateServiceWorker()

console.log('\n🎨 Icons Validation:')
validateIcons()

console.log('\n📝 HTML Validation:')
validateIndexHTML()

console.log('\n🔧 Service Worker Registration Validation:')
validateServiceWorkerRegistration()

console.log('\n' + '='.repeat(50))
if (errors === 0 && warnings === 0) {
  console.log('✅ All PWA requirements met!')
  process.exit(0)
} else {
  console.log(`Results: ${errors} error(s), ${warnings} warning(s)`)
  if (errors > 0) {
    console.log('❌ PWA validation failed')
    process.exit(1)
  } else {
    console.log('⚠️  PWA validation passed with warnings')
    process.exit(0)
  }
}
