#!/usr/bin/env node
/**
 * PWA Validation Script
 * Validates that all PWA requirements are met
 */

const fs = require('fs')
const path = require('path')

const publicDir = path.join(__dirname, '../public')

let errors = 0
let warnings = 0

function checkFile(filePath, description) {
  if (fs.existsSync(filePath)) {
    console.log(`✅ ${description}`)
    return true
  } else {
    console.error(`❌ ${description} - File not found: ${filePath}`)
    errors++
    return false
  }
}

function validateJSON(filePath, description) {
  try {
    const content = fs.readFileSync(filePath, 'utf8')
    JSON.parse(content)
    console.log(`✅ ${description} - Valid JSON`)
    return true
  } catch (e) {
    console.error(`❌ ${description} - Invalid JSON: ${e.message}`)
    errors++
    return false
  }
}

function validateManifest() {
  const manifestPath = path.join(publicDir, 'manifest.json')
  if (!checkFile(manifestPath, 'Manifest file exists')) return
  if (!validateJSON(manifestPath, 'Manifest JSON')) return

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'))

  // Check required fields
  const requiredFields = ['name', 'short_name', 'start_url', 'display', 'icons']
  requiredFields.forEach((field) => {
    if (manifest[field]) {
      console.log(`✅ Manifest has '${field}' field`)
    } else {
      console.error(`❌ Manifest missing required field: '${field}'`)
      errors++
    }
  })

  // Check icons
  if (Array.isArray(manifest.icons) && manifest.icons.length > 0) {
    console.log(`✅ Manifest has ${manifest.icons.length} icon(s)`)
  } else {
    console.error('❌ Manifest has no icons')
    errors++
  }
}

function validateServiceWorker() {
  // Service worker (sw.js) is auto-generated by vite-plugin-pwa during build
  // Check if dist directory exists and contains sw.js
  const distDir = path.join(__dirname, '../dist')
  const swPath = path.join(distDir, 'sw.js')

  if (!fs.existsSync(distDir)) {
    console.log(
      '⚠️  Service worker not yet generated (run "npm run build" first)'
    )
    warnings++
    return
  }

  if (!fs.existsSync(swPath)) {
    console.error('❌ Service worker file (sw.js) not found in dist/')
    errors++
    return
  }

  console.log('✅ Service worker file (sw.js) generated by vite-plugin-pwa')

  const content = fs.readFileSync(swPath, 'utf8')

  // Check for Workbox presence (generated by vite-plugin-pwa)
  if (content.includes('workbox') || content.includes('precache')) {
    console.log('✅ Service worker uses Workbox for caching')
  } else {
    console.error('❌ Service worker missing Workbox configuration')
    errors++
  }
}

function validateIcons() {
  const icons = ['icon-192x192.svg', 'icon-512x512.svg']
  icons.forEach((icon) => {
    checkFile(path.join(publicDir, icon), `Icon file: ${icon}`)
  })
}

function validateIndexHTML() {
  const indexPath = path.join(publicDir, 'index.html')
  if (!checkFile(indexPath, 'index.html exists')) return

  const content = fs.readFileSync(indexPath, 'utf8')

  // Check for theme-color
  if (content.includes('name="theme-color"')) {
    console.log('✅ index.html has theme-color meta tag')
  } else {
    console.warn('⚠️  index.html missing theme-color meta tag')
    warnings++
  }

  // Check built version for manifest link (injected by vite-plugin-pwa)
  const distDir = path.join(__dirname, '../dist')
  const distIndexPath = path.join(distDir, 'index.html')

  if (fs.existsSync(distIndexPath)) {
    const distContent = fs.readFileSync(distIndexPath, 'utf8')
    if (distContent.includes('rel="manifest"')) {
      console.log(
        '✅ Built index.html links to manifest (injected by vite-plugin-pwa)'
      )
    } else {
      console.error('❌ Built index.html missing manifest link')
      errors++
    }
  } else {
    console.log('⚠️  Built index.html not found (run "npm run build" first)')
    warnings++
  }
}

function validateServiceWorkerRegistration() {
  // Check that vite-plugin-pwa is configured (not a build artifact check)
  // The actual registerSW.js is generated during build by vite-plugin-pwa
  const viteConfigPath = path.join(__dirname, '../vite.config.js')

  if (!checkFile(viteConfigPath, 'Vite config exists')) {
    return
  }

  const content = fs.readFileSync(viteConfigPath, 'utf8')

  if (content.includes('VitePWA') && content.includes('registerType')) {
    console.log('✅ Service worker registration configured (vite-plugin-pwa)')
  } else {
    console.error('❌ vite-plugin-pwa not configured in vite.config.js')
    errors++
  }
}

console.log('🔍 Validating PWA Implementation...\n')

console.log('📄 Manifest Validation:')
validateManifest()

console.log('\n⚙️  Service Worker Validation:')
validateServiceWorker()

console.log('\n🎨 Icons Validation:')
validateIcons()

console.log('\n📝 HTML Validation:')
validateIndexHTML()

console.log('\n🔧 Service Worker Registration Validation:')
validateServiceWorkerRegistration()

console.log('\n' + '='.repeat(50))
if (errors === 0 && warnings === 0) {
  console.log('✅ All PWA requirements met!')
  process.exit(0)
} else {
  console.log(`Results: ${errors} error(s), ${warnings} warning(s)`)
  if (errors > 0) {
    console.log('❌ PWA validation failed')
    process.exit(1)
  } else {
    console.log('⚠️  PWA validation passed with warnings')
    process.exit(0)
  }
}
